/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

import {
  CircuitZKit,
  CircuitZKitConfig,
  Groth16Proof,
  NumberLike,
  NumericString,
  PublicSignals,
} from "@solarity/zkit";

export type Privateverify = {
  root: NumberLike;
  r: NumberLike[];
  s: NumberLike[];
  pk: NumberLike[][];
  proof: NumberLike[];
  path: NumberLike[];
};

export type Publicverify = {
  out: NumericString;
  root: NumericString;
};

export type Proofverify = {
  proof: Groth16Proof;
  publicSignals: Publicverify;
};

export type Calldata = [
  [NumericString, NumericString],
  [[NumericString, NumericString], [NumericString, NumericString]],
  [NumericString, NumericString],
  [NumericString, NumericString],
];

export class verify extends CircuitZKit {
  constructor(config: CircuitZKitConfig) {
    super(config);
  }

  public async generateProof(inputs: Privateverify): Promise<Proofverify> {
    const proof = await super.generateProof(inputs as any);

    return {
      proof: proof.proof,
      publicSignals: this._normalizePublicSignals(proof.publicSignals),
    };
  }

  public async verifyProof(proof: Proofverify): Promise<boolean> {
    return await super.verifyProof({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public async generateCalldata(proof: Proofverify): Promise<Calldata> {
    return await super.generateCalldata({
      proof: proof.proof,
      publicSignals: this._denormalizePublicSignals(proof.publicSignals),
    });
  }

  public getSignalNames(): string[] {
    return ["out", "root"];
  }

  private _normalizePublicSignals(publicSignals: PublicSignals): Publicverify {
    const signalNames = this.getSignalNames();

    return signalNames.reduce((acc: any, signalName, index) => {
      acc[signalName] = publicSignals[index];
      return acc;
    }, {});
  }

  private _denormalizePublicSignals(
    publicSignals: Publicverify,
  ): PublicSignals {
    const signalNames = this.getSignalNames();

    return signalNames.map((signalName) => (publicSignals as any)[signalName]);
  }
}

export default verify;
